module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bbcac5",
        "tertiary": "#9b4429",
        "secondary-fixed-dim": "#a1d0c6",
        "on-secondary-fixed": "#00201c",
        "on-secondary-container": "#406c64",
        "secondary-fixed": "#bcece2",
        "primary": "#006b5f",
        "tertiary-fixed": "#ffdbd1",
        "tertiary-fixed-dim": "#ffb59f",
        "primary-container": "#04ae9c",
        "surface-container-high": "#e6e8ea",
        "primary-fixed": "#75f8e3",
        "surface-dim": "#d8dadc",
        "on-primary-fixed": "#00201c",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#006b5f",
        "on-primary": "#ffffff",
        "inverse-primary": "#55dbc7",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#611a02",
        "on-surface-variant": "#3c4946",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "secondary": "#3a665f",
        "on-primary-container": "#003a33",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#005047",
        "secondary-container": "#bcece2",
        "on-tertiary-fixed-variant": "#7c2d14",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#3a0a00",
        "surface-container": "#eceef0",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#55dbc7",
        "on-secondary-fixed-variant": "#204e47",
        "outline": "#6c7a76",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "surface": "#f7f9fb",
        "tertiary-container": "#e77e5e"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"]
      }
    },
  },
  plugins: [],
}
