"""
arxiv-watcher Skill - Generated by ClawHub Skill Deployer
"""
from .base import BaseSkill
from .discovery import skill
import requests
import xml.etree.ElementTree as ET
from urllib.parse import quote_plus
import re
import time


@skill
class ArxivWatcherSkill(BaseSkill):
    name = "arxiv-watcher"
    description = "Search and summarize papers from ArXiv. Use when the user asks for the latest research, specific topics on ArXiv, or a daily summary of AI papers."
    version = "1.3.0"
    
    @property
    def instructions(self):
        try:
            from pathlib import Path
            skill_dir = Path(__file__).parent.parent.parent / "skills" / "arxiv-watcher"
            skill_md = skill_dir / "SKILL.md"
            if skill_md.exists():
                with open(skill_md, 'r', encoding='utf-8') as f:
                    return f.read()
        except Exception:
            pass
        return super().instructions
    
    def _clean_query(self, query: str) -> str:
        """移除中文字符和其他非英文字符，只保留英文关键词"""
        cleaned = re.sub(r'[^\x00-\x7F]+', ' ', query)
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()
        return cleaned
    
    def _build_precise_query(self, keywords: str) -> str:
        """
        构建精准查询：用 AND 连接关键词，确保所有词都必须出现
        优先搜索标题(ti:)，其次摘要(abs:)
        """
        # 按空格拆分关键词
        terms = keywords.split()
        if not terms:
            return f"all:{quote_plus(keywords)}"
        
        # 方案 A: 标题中包含所有关键词（最精准）
        ti_query = " AND ".join([f"ti:{quote_plus(term)}" for term in terms])
        
        # 方案 B: 标题或摘要中包含所有关键词（稍宽泛）
        # abs_query = " AND ".join([f"(ti:{quote_plus(term)} OR abs:{quote_plus(term)})" for term in terms])
        
        # 当前使用方案 A，如需更宽泛可切换为方案 B
        return ti_query
    
    def execute(self, query="", max_results=100, **kwargs):
        """
        Execute ArXiv search - precise matching, full results
        """
        if not query:
            query = kwargs.get("query", "deep learning")
        
        print(f"[arxiv-watcher DEBUG] Original query: {query}")
        
        try:
            # Step 1: 清洗查询
            cleaned_query = self._clean_query(query)
            print(f"[arxiv-watcher DEBUG] Cleaned query: '{cleaned_query}'")
            
            if not cleaned_query:
                return {
                    "success": False,
                    "error": "Query contains no valid English keywords for ArXiv search.",
                    "query": query
                }
            
            # Step 2: 构建精准查询（所有关键词必须同时出现）
            search_query = self._build_precise_query(cleaned_query)
            print(f"[arxiv-watcher DEBUG] Precise query: {search_query}")
            
            base_url = "https://export.arxiv.org/api/query"
            params = {
                "search_query": search_query,
                "start": 0,
                "max_results": max_results,
                "sortBy": "relevance",
                "sortOrder": "descending"
            }
            
            # 使用 requests 的 params 参数自动处理 URL 编码
            print(f"[arxiv-watcher DEBUG] Request params: {params}")
            
            # Step 3: 发送请求 - 添加重试机制和延迟
            max_retries = 3
            retry_delay = 2
            response = None
            
            for attempt in range(max_retries):
                try:
                    print(f"[arxiv-watcher DEBUG] Attempt {attempt + 1}/{max_retries}")
                    if attempt > 0:
                        time.sleep(retry_delay * attempt)  # 指数退避
                    
                    response = requests.get(base_url, params=params, timeout=30)
                    print(f"[arxiv-watcher DEBUG] Response status: {response.status_code}")
                    
                    if response.status_code == 429:
                        print(f"[arxiv-watcher WARN] Rate limited, waiting before retry...")
                        if attempt < max_retries - 1:
                            continue
                    
                    response.raise_for_status()
                    break  # 成功，跳出循环
                    
                except requests.exceptions.HTTPError as e:
                    if response and response.status_code == 429 and attempt < max_retries - 1:
                        print(f"[arxiv-watcher WARN] 429 error, retrying...")
                        continue
                    raise
            
            # Step 4: 解析 XML
            root = ET.fromstring(response.content)
            namespace = {"atom": "http://www.w3.org/2005/Atom"}
            entries = root.findall(".//atom:entry", namespace)
            
            papers = []
            for idx, entry in enumerate(entries, 1):
                title = entry.find(".//atom:title", namespace)
                summary = entry.find(".//atom:summary", namespace)
                published = entry.find(".//atom:published", namespace)
                authors = entry.findall(".//atom:author/atom:name", namespace)
                categories = entry.findall(".//atom:category", namespace)
                links = entry.findall(".//atom:link", namespace)
                
                # 提取 URL
                pdf_url = None
                abs_url = None
                for link in links:
                    href = link.get("href", "")
                    title_attr = link.get("title", "")
                    if title_attr == "pdf" or "/pdf/" in href:
                        pdf_url = href
                    elif "abs/" in href:
                        abs_url = href
                
                if not abs_url and links:
                    abs_url = links[0].get("href", "")
                
                paper = {
                    "index": idx,  # 🔹 添加序号，方便前端展示
                    "title": title.text.strip() if title is not None else "",
                    "summary": summary.text.strip() if summary is not None else "",
                    "published": published.text.strip() if published is not None else "",
                    "authors": [a.text.strip() for a in authors if a is not None],
                    "categories": [c.get("term", "") for c in categories if c is not None],
                    "pdf_url": pdf_url,
                    "abs_url": abs_url
                }
                papers.append(paper)
            
            print(f"[arxiv-watcher DEBUG] Found {len(papers)} papers")
            
            # 🔹 返回结构优化：添加总数和清晰列表
            return {
                "success": True,
                "query": query,
                "cleaned_query": cleaned_query,
                "search_query_used": search_query,  # 🔹 方便调试实际搜索语句
                "total_found": len(papers),
                "max_results_requested": max_results,
                "papers": papers  # 🔹 完整列表，前端可遍历展示所有
            }
            
        except Exception as e:
            print(f"[arxiv-watcher ERROR] Failed to search ArXiv: {e}")
            import traceback
            traceback.print_exc()
            return {
                "success": False,
                "error": str(e),
                "query": query
            }